/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Daniel
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        ProgramList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        InstructionTree = new javax.swing.JTree();
        jToolBar2 = new javax.swing.JToolBar();
        AddBut = new javax.swing.JButton();
        DelBut = new javax.swing.JButton();
        EditBut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        StartBut = new javax.swing.JButton();
        PauseBut = new javax.swing.JButton();
        StopBut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        NewItm = new javax.swing.JMenuItem();
        OpenItm = new javax.swing.JMenuItem();
        SaveItm = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arduino Control App");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ProgramList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ProgramList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jScrollPane2.setViewportView(InstructionTree);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        AddBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        AddBut.setToolTipText("Añadir instrucción al programa");
        AddBut.setFocusable(false);
        AddBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddBut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(AddBut);

        DelBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N
        DelBut.setToolTipText("Borrar instrucción seleccionada");
        DelBut.setFocusable(false);
        DelBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DelBut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(DelBut);

        EditBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        EditBut.setToolTipText("Editar valor de instrucción");
        EditBut.setFocusable(false);
        EditBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditBut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(EditBut);
        jToolBar2.add(jSeparator1);

        StartBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        StartBut.setToolTipText("Ejecutar programa");
        StartBut.setFocusable(false);
        StartBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StartBut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(StartBut);

        PauseBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pause.png"))); // NOI18N
        PauseBut.setToolTipText("Pausar ejecución");
        PauseBut.setFocusable(false);
        PauseBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PauseBut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(PauseBut);

        StopBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop.png"))); // NOI18N
        StopBut.setToolTipText("Parar ejecución");
        StopBut.setFocusable(false);
        StopBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StopBut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(StopBut);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jToolBar2, gridBagConstraints);

        jMenu1.setText("Archivo");

        NewItm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewItm.setText("Nuevo");
        jMenu1.add(NewItm);

        OpenItm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenItm.setText("Abrir");
        jMenu1.add(OpenItm);

        SaveItm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveItm.setText("Guardar");
        jMenu1.add(SaveItm);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBut;
    private javax.swing.JButton DelBut;
    private javax.swing.JButton EditBut;
    private javax.swing.JTree InstructionTree;
    private javax.swing.JMenuItem NewItm;
    private javax.swing.JMenuItem OpenItm;
    private javax.swing.JButton PauseBut;
    private javax.swing.JList<String> ProgramList;
    private javax.swing.JMenuItem SaveItm;
    private javax.swing.JButton StartBut;
    private javax.swing.JButton StopBut;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
